In [10]:
import requests
import altair as alt
from vega_datasets import data
import pandas as pd

# import urllib library
from urllib.request import urlopen
import json

In [58]:
states = alt.topo_feature(data.us_10m.url, feature='states')
states

UrlData({
  format: TopoDataFormat({
    feature: 'states',
    type: 'topojson'
  }),
  url: 'https://cdn.jsdelivr.net/npm/vega-datasets@v1.29.0/data/us-10m.json'
})

In [40]:
f = urlopen('https://raw.githubusercontent.com/tbrugz/geodata-br/master/geojson/geojs-100-mun.json')
ff = json.loads(f.read())

In [21]:
finished = pd.read_csv('../data/finished.csv')

In [44]:
for i in ff['features']:
    if i['properties']['name'] in list(finished['estado'].unique()):
        a['features'].append(i)

In [43]:
a = ff.copy()
a['features'] = []

In [46]:
for i in a['features']:
    print(i['properties']['name'])

Amapá
Espírito Santo
Paraná
Mato Grosso
Tocantins
Rio de Janeiro
São Paulo
Goiás

In [79]:
finished.head()

est_abb = pd.read_csv('cod_abb_estado.CSV', sep=';', encoding="ISO-8859-1")

estado_cod = {est_abb['Estado'][i]: est_abb['Código da UF'][i] for i in range(len(est_abb))}
estado_cod
finished['codigo'] = finished['estado'].apply(lambda x: str(estado_cod[x]))
cols = list(finished.columns)
finished = finished[cols[:2] + [cols[-1]] + cols[2:-1]].copy()

{'Acre': 12,
 'Alagoas': 27,
 'Amazonas': 13,
 'Amapá': 16,
 'Bahia': 29,
 'Ceará': 23,
 'Distrito Federal': 53,
 'Espírito Santo': 32,
 'Goiás': 52,
 'Maranhão': 21,
 'Minas Gerais': 31,
 'Mato Grosso do Sul': 50,
 'Mato Grosso': 51,
 'Pará': 15,
 'Paraíba': 25,
 'Pernambuco': 26,
 'Piauí': 22,
 'Paraná': 41,
 'Rio de Janeiro': 33,
 'Rio Grande do Norte': 24,
 'Rondônia': 11,
 'Roraima': 14,
 'Rio Grande do Sul': 43,
 'Santa Catarina': 42,
 'Sergipe': 28,
 'São Paulo': 35,
 'Tocantins': 17}

['region',
 'estado',
 'codigo',
 'latitude',
 'longitude',
 'ano',
 'mes',
 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)',
 'Temperatura Média (°C)',
 'area',
 'desmatado',
 'incremento',
 'floresta',
 'nuvem',
 'nao_observado',
 'nao_floresta',
 'hidrografia',
 'n_incendios']

In [87]:
finished['codigo'] = finished['estado'].apply(lambda x: str(estado_cod[x]))
finished.head()

,region,estado,latitude,longitude,ano,mes,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)",Temperatura Média (°C),area,desmatado,incremento,floresta,nuvem,nao_observado,nao_floresta,hidrografia,n_incendios,codigo
0,Norte,Acre,-9.957778,-68.165,1998,Janeiro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,12
1,Norte,Acre,-9.957778,-68.165,1998,Fevereiro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,12
2,Norte,Acre,-9.957778,-68.165,1998,Março,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,12
3,Norte,Acre,-9.957778,-68.165,1998,Abril,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,12
4,Norte,Acre,-9.957778,-68.165,1998,Maio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,12

In [89]:
bala = finished.groupby('codigo', as_index=False)['incremento'].sum()
bala

   codigo  incremento
0      11     32176.7
1      12      9294.2
2      13     17807.9
3      14      5860.4
4      15    104912.3
5      16      1481.8
6      17      1961.2
7      21     36347.8
8      22         0.0
9      23         0.0
10     24         0.0
11     25         0.0
12     26         0.0
13     27         0.0
14     28         0.0
15     29         0.0
16     31         0.0
17     32         0.0
18     33         0.0
19     35         0.0
20     41         0.0
21     42         0.0
22     43         0.0
23     50         0.0
24     51    136258.8
25     52         0.0
26     53         0.0

In [57]:
source = data.unemployment.url
tsv = pd.read_csv(source, sep="\t")
tsv.head()

     id   rate
0  1001  0.097
1  1003  0.091
2  1005  0.134
3  1007  0.121
4  1009  0.099

In [104]:
f = "https://raw.githubusercontent.com/fititnt/gis-dataset-brasil/master/uf/geojson/uf.json"

data_geojson_remote = alt.Data(url=f, format=alt.DataFormat(property='features',type='json'))

alt.Chart(data_geojson_remote).mark_geoshape(
    stroke='lightgray'
).encode(
    color='incremento:Q'
).transform_lookup(
    lookup="properties.GEOCODIGO",
    from_=alt.LookupData(data=bala, key="codigo", fields=['incremento'])
)#.interactive()

alt.Chart(...)

In [71]:
afa

  GEOCODIGO  rate
0        41  9.94

In [20]:
link = "http://noticias.gov.br/noticias-api/noticias/busca?b=incendios&wt=json"
H = 0
link = f'http://noticias.gov.br/noticias-api/noticias/busca?b=titulo:incendio%20titulo:amazonas&h={H}&wt=json'
request = requests.get(link)

In [8]:
for i in request.json()["resultado"]["noticias"]["noticia"]:
    with st.exp

{'id': 38960368,
 'titulo': 'Dados Abertos',
 'fonte': 'Portal Brasil',
 'dataDePublicacao': 'Thu Sep 22 00:00:00 BRT 2016',
 'link': 'http://www.brasil.gov.br/meio-ambiente/2016/09/rede-panamazonica-de-protecao-socioambiental-e-criada-em-brasilia/amazonia.jpg/view/',
 'resumo': ' Temer sanciona lei que prorroga registro no Cadastro Ambiental Rural (CAR) para dezembro de 2017\n<a href="https://www.youtube.com/watch?v=wSBFwp9vVgE">Brasil já registrou 112 mil focos de queimadas e incêndios neste ano</a>\nBrasil já registrou 112 mil',
 'idFonte': 3706,
 'descricao': 'Clique para ver a imagem no tamanho completo… — Tamanho: 411KB\n\nÚltimas notícias Rede Panamazônica de proteção socioambiental é criada em Brasília ICMBio edita plano de proteção da Serra das Araras (MT) Está suspenso o uso da água do rio São Mateus (ES/MG) Paraná firma contrato para divulgar dados sobre qualidade de água Governo brasileiro apresenta ações ambientais em NY Últimas notícias - Mais…\n\nÚltimos vídeos\nPrazo para registro no Cadastro Ambiental Rural é prorrogado\nPresidente Michel Temer sanciona lei que prorroga registro no Cadastro Ambiental Rural (CAR) para dezembro de 2017\n<a href="https://www.youtube.com/watch?v=wSBFwp9vVgE">Brasil já registrou 112 mil focos de queimadas e incêndios neste ano</a>\nBrasil já registrou 112 mil focos de queimadas e incêndios neste ano\nDados são do Instituto Nacional de Pesquisas Espaciais (INPE). Registro é 16% maior que o registrado no mesmo período do ano passado.\n\n<a href="https://www.youtube.com/watch?v=_yftuyoQpcQ">Conheça a proposta do Santuário de Baleias do Atlântico Sul</a>\nConheça a proposta do Santuário de Baleias do Atlântico Sul\nPara proteger a população das diferentes espécies de baleias da região do Atlântico Sul, o Brasil, a Argentina, a África do Sul, o Uruguai e o Gabão estão propondo a criação do santuário\n\nPrazo para registro no Cadastro Ambiental Rural é prorrogado\nBrasil já registrou 112 mil focos de queimadas e incêndios neste ano\nConheça a proposta do Santuário de Baleias do Atlântico Sul\nacesse a lista completa\nÚltimas imagens\nAmazônia\nA participação no grupo está aberta a todos os países do bioma\nJefferson Rudy/MMA\nPrêmio Nacional da Biodiversidade 2ª Edição\nTrês candidaturas serão finalistas em cada uma das sete categorias\nDivulgação/ICMBio\nICMBio cria 225 reservas particulares em nove anos\nEstabelecidas por decreto em 1990, as RPPNs passaram a ser consideradas unidades de conservação no ano 2000\nDivulgação/ICMBio\nEntenda o trabalho de monitoramento de incêndios no País\nSerra da Canastra, em Minas Gerais\nUm helicóptero, cedido pelo governo estadual, e oito veículos ajudam no transporte de pessoal\nDivulgação/ICMBio\n« Anterior\nPróximo »\n« Anterior\nPróximo »\nacesse a lista completa\nVoltar para o topo\nDesenvolvido com o CMS de código aberto Plone\n\n'}

In [30]:
request.json()["resultado"]["noticias"]#["noticia"]#[0]['titulo']

{'noticia': {'id': 29447850,
  'titulo': 'Sul do Amazonas está mais vulnerável a incêndios, aponta pesquisa',
  'fonte': 'Ministério da Ciência e Tecnologia',
  'dataDePublicacao': 'Mon Jan 21 00:00:00 BRST 2013',
  'link': 'http://www.mct.gov.br/index.php/content/view/344952/Sul_do_Amazonas_esta_mais_vulneravel_a_incendios_aponta_pesquisa.html',
  'resumo': ' Boa do Acre e Lábrea, sul do Amazonas, está mais propícia a incêndios florestais recorrentes. A constatação foi feita após coleta de dados no campo e análises de imagens de satélite referentes a 11 anos da história de fogo na área.\n\nDe acordo com',
  'idFonte': 5,
  'descricao': '21/01/2013 - 14:26\n\nUma pesquisa da engenheira agrônoma Sumaia Vasconcelos, aluna de doutorado do Instituto Nacional de Pesquisas da Amazônia (Inpa/MCTI), revelou que uma área de aproximadamente 86.600 hectares de floresta em pé nos municípios de Boa do Acre e Lábrea, sul do Amazonas, está mais propícia a incêndios florestais recorrentes. A constatação foi feita após coleta de dados no campo e análises de imagens de satélite referentes a 11 anos da história de fogo na área.\n\nDe acordo com Sumaia, o local foi impactado por grandes incêndios florestais ocorridos durante a seca de 2005. Ela explica que esses incêndios geralmente são causados pela prática humana de atear fogo em áreas já cultivadas (como cultivos agrícolas e pastagens) que saem do controle e invadem a floresta. A pesquisadora disse que se o clima mudar como previsto por modelos de circulação global (MCG) na região, o uso descontrolado do fogo pelo homem, aliado a esse fator, pode ocasionar novos incêndios florestais de maior magnitude.\n\n“O impacto pode ser duas vezes maior que no primeiro incêndio. No incêndio de 2005 a estimativa de carbono comprometido para emissões foi de 1,8 e 2,2 milhões de toneladas, um e quatro anos depois do fogo”, comenta.\n\nO estudo revelou também que a região sul do Amazonas concentra 60% dos focos de calor (indicador de queimada) de todo o estado. Além de Lábrea e Boca do Acre, Apuí, Novo Aripuanã, Manicoré, Humaitá e Canutama registram alto índice de focos de calor. Sumaia Vasconcelos explica que os picos desses focos ocorrem em período de menos chuva.\n\n“Essa região concentrou cerca de 60% dos focos de calor detectados no Amazonas de 2000 a 2010. Ao longo desses 11 anos esses municípios foram os campeões de queimadas”, destaca. “A maior ocorrência de focos de calor incidiu em área com precipitação de chuva inferior a 100 milímetros por mês. É uma região mais seca, comparada ao norte e noroeste do Amazonas, mas na Amazônia, além do fator meteorológico, o fogo, para existir, geralmente precisa ter o homem como fonte de ignição. Há forte pressão do uso da terra nessa região.”\n\n'}}